"""
PDF Generator for SAR Reports
Converts SAR narrative text into a professionally formatted PDF document.
"""

from fpdf import FPDF
from datetime import datetime
import re


def _sanitize_text(text):
    """Replace Unicode characters unsupported by Helvetica/latin-1."""
    if not text:
        return ""
    text = str(text)
    replacements = {
        '\u20b9': 'INR ',   # ₹
        '\u20ac': 'EUR ',   # €
        '\u00a3': 'GBP ',   # £
        '\u00a5': 'JPY ',   # ¥
        '\u2013': '-',      # –
        '\u2014': '--',     # —
        '\u2018': "'",      # '
        '\u2019': "'",      # '
        '\u201c': '"',      # "
        '\u201d': '"',      # "
        '\u2022': '-',      # •
        '\u2026': '...',    # …
        '\u2192': '->',     # →
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    text = text.encode('latin-1', errors='replace').decode('latin-1')
    return text


_SECTION_RE = re.compile(r'^(SECTION\s+\d+|\d{1,2}\.\s+[A-Z])', re.IGNORECASE)


def generate_sar_pdf(narrative_text, case_id="N/A", customer_name="N/A",
                     risk_level="N/A", risk_score=0):
    """Generate a PDF from SAR narrative text. Returns bytes."""

    narrative_text = _sanitize_text(narrative_text)
    case_id = _sanitize_text(case_id)
    customer_name = _sanitize_text(customer_name)
    risk_level = _sanitize_text(risk_level)

    pdf = FPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # Available width
    w = pdf.w - pdf.l_margin - pdf.r_margin

    # Header bar
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(180, 0, 0)
    pdf.cell(w=w, h=6, text="CONFIDENTIAL - SUSPICIOUS ACTIVITY REPORT", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(180, 0, 0)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(6)

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(w=w, h=12, text="Suspicious Activity Report (SAR)", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Meta info
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(40, 40, 40)
    meta = [
        f"Case ID: {case_id}    |    Entity: {customer_name}",
        f"Risk Level: {risk_level}    |    Risk Score: {risk_score}/100",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    ]
    for line in meta:
        pdf.cell(w=w, h=6, text=line, fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # Divider
    pdf.set_draw_color(180, 0, 0)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(6)

    # Body
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)

    for line in narrative_text.split("\n"):
        stripped = line.strip()
        if not stripped:
            pdf.ln(3)
            continue

        # Detect section headings
        is_heading = False
        if _SECTION_RE.match(stripped):
            is_heading = True
        elif stripped.startswith("SUSPICIOUS ACTIVITY REPORT"):
            is_heading = True
        elif stripped.isupper() and len(stripped) > 15:
            is_heading = True
        elif stripped.startswith("#"):
            is_heading = True
            stripped = stripped.lstrip("#").strip()

        if is_heading:
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(140, 0, 0)
            pdf.multi_cell(w=w, h=6, text=stripped)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.ln(1)
        else:
            pdf.multi_cell(w=w, h=5, text=stripped)

    # Footer note
    pdf.ln(8)
    pdf.set_draw_color(180, 0, 0)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(128, 128, 128)
    pdf.multi_cell(w=w, h=4, text="This document is generated by FinSentry AI SAR Generation System. "
                   "It is confidential and intended solely for regulatory filing purposes.")

    return bytes(pdf.output())
